Controllers/BackendController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieTheater.Data;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Session;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieTheater.Models;

namespace MovieTheater.Controllers
{
    public sealed class BackendController : Controller
    {
        private readonly WebContext _context;

        public
        BackendController(WebContext context) => _context = context;

        public IActionResult
        Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("user_group")))
                return RedirectToAction("ALogin", "UserGate");
            if (HttpContext.Session.GetString("user_group").Equals("admin"))
                return View();
            else
                return RedirectToAction("ALogin", "UserGate");
        }

        public IActionResult
        Create()
        {
            ViewBag.movie_category_id = _context.MovieCategories;
            ViewBag.movie_country_id  = _context.MovieCountries;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
        Create(int id,
              [Bind("MovieId,MovieName," +
                    "MovieActor," +
                    "MovieDescription," +
                    "MovieDirector," +
                    "MovieGrade," +
                    "MovieImg," +
                    "MoviePrice," +
                    "MovieCategoryId," +
                    "MovieCountryId")]
            Movie movie)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _context.AddAsync(movie);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(MovieManageIndex));
                }
            } catch (Exception)
            {
                Console.WriteLine("Update Error.");
                throw;
            }
            return View(movie);
        }
        
        public async Task<IActionResult>
        MovieManageIndex(string sortOrder, string searchString)
        {

            if (HttpContext.Session.GetString("user_group") != "admin")
                return RedirectToAction(nameof(Index));

            ViewData["NameSortParm"]  = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["GradeSortParm"] = sortOrder == "Grade" ? "grade_desc" : "grade";
            ViewData["CurrentFilter"] = searchString;

            var movies = _context.Movies
                                 .Include(m => m.movie_category)
                                 .Include(m => m.movie_country)
                                 .AsNoTracking();

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(m => m.MovieName.Contains(searchString) ||
                                           m.MovieDescription.Contains(searchString) ||
                                           m.MovieDirector.Contains(searchString) ||
                                           m.MovieActor.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    movies = movies.OrderByDescending(m => m.MovieName);
                    break;
                case "grade":
                    movies = movies.OrderBy(m => m.MovieGrade);
                    break;
                case "grade_desc":
                    movies = movies.OrderByDescending(m => m.MovieGrade);
                    break;
                default:
                    movies = movies.OrderBy(m => m.MovieName);
                    break;
            }

            return View(await movies.AsNoTracking().ToListAsync());
        }

        public async Task<IActionResult>
        MovieEdit(int? id)
        {
            if (id == null)    return NotFound();
            
            var movie = await _context.Movies.Include(m => m.movie_category)
                                             .Include(m => m.movie_country)
                                      .SingleOrDefaultAsync(m => m.MovieId == id);
            ViewBag.movieCategory = _context.MovieCategories;
            ViewBag.movieCountry  = _context.MovieCountries;
            
            if (movie == null) return NotFound();
            return View(movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
        MovieEdit(int id,
                  [Bind("MovieId,MovieName," +
                        "MovieActor," +
                        "MovieDescription," +
                        "MovieDirector," +
                        "MovieGrade," +
                        "MovieImg," +
                        "MoviePrice," +
                        "MovieCategoryId," +
                        "MovieCountryId")]
                  Movie movie)
        {
            if (id != movie.MovieId) return NotFound();
            if (!ModelState.IsValid) return View(movie);
            
            try
            {
                _context.Update(movie);
                await _context.SaveChangesAsync();
            } catch (Exception)
            {
                if (!_context.Movies.Any(m => m.MovieId == movie.MovieId)) return NotFound();
                else                                                       throw;
            }

            return RedirectToAction(nameof(MovieManageIndex));
        }

        public async Task<IActionResult>
        MovieDetails(int? id)
        {
            if (id == null)    return NotFound();
            
            var movie = await _context.Movies.Include(m => m.movie_category)
                                             .Include(m => m.movie_country)
                                      .AsNoTracking()
                                      .SingleOrDefaultAsync(m => m.MovieId == id);

            if (movie == null) return NotFound();
            return View(movie);
        }
    
        public async Task<IActionResult>
        MovieDelete(int? id, bool? saveChangesError = false)
        {
            if (id == null)    return NotFound();

            var movie = await _context.Movies
                                      .AsNoTracking()
                                      .SingleOrDefaultAsync(m => m.MovieId == id);

            if (movie == null) return NotFound();

            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                "Delete failed. Try again, and if the problem persists " +
                "see your system administrator.";
            }

            return View(movie);
        }
    
        public async Task<IActionResult>
        DeleteConfirm(int id)
        {
            var movie = await _context.Movies.AsNoTracking()
                                             .SingleOrDefaultAsync(m => m.MovieId == id);
            if (movie == null) return RedirectToAction(nameof(MovieManageIndex));

            try
            {
                _context.Movies.Remove(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(MovieManageIndex));
            } catch (DbUpdateException)
            {
                return RedirectToAction(nameof(MovieDelete), new {id = id});
            }
        }
    
        public async Task<IActionResult>
        CategoryManageIndex()
        {
            if (!HttpContext.Session.GetString("user_group").Equals("admin"))
                return RedirectToAction("Index", "Home");
            return View(await _context.MovieCategories
                                      .AsNoTracking()
                                      .ToListAsync());
        }

        public IActionResult
        CreateCategory()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
        CreateCategory(int id,
                       [Bind("CategoryId,CategoryName")] MovieCategory category)
        {
            if (id != category.CategoryId)
                return NotFound();
            
            if (ModelState.IsValid)
            {
                try
                {
                    await _context.AddAsync(category);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(CategoryManageIndex));
                } catch (Exception)
                {
                    Console.WriteLine("Category Create Error.");
                    throw;
                }
            }
            return View(category);
        }

        public async Task<IActionResult>
        CountryManageIndex()
        {
            if (!HttpContext.Session.GetString("user_group").Equals("admin"))
                return RedirectToAction("Index", "Home");
            return View(await _context.MovieCountries
                                      .AsNoTracking()
                                      .ToListAsync());
        }
    
        public IActionResult
        CreateCountry()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
        CreateCountry(int id,
                      [Bind("CountryId,CountryName")] MovieCountry country)
        {
            if (id != country.CountryId)
                return NotFound();
            
            if (ModelState.IsValid)
            {
                try
                {
                    await _context.AddAsync(country);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(CountryManageIndex));
                } catch (Exception)
                {
                    Console.WriteLine("Create Country error.");
                    throw;

Controllers/RankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieTheater.Data;
using Microsoft.EntityFrameworkCore;
using MovieTheater.Models;

namespace MovieTheater.Controllers
{
    public class RankController : Controller
    {
        private readonly WebContext _context;
        public RankController(WebContext context) => _context = context;

        public async Task<IActionResult>
        Index()
        {
            var movies = await _context.Movies
                                       .AsNoTracking()
                                       .OrderByDescending(m => m.MovieGrade)
                                       .ToListAsync();
            movies.Sort(new MovieGradeComparer());
            var top_movies = new List<Movie>();
            
            for (int i=0; i<10; i++)
                top_movies.Add(movies[i]);
                
            return View(top_movies);
        }
    }
}

//Todo

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieTheater</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MovieTheater</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">首页</a></li>
                    <li><a asp-area="" asp-controller="Movie" asp-action="Index">电影</a></li>
                    <li><a asp-area="" asp-controller="Rank" asp-action="Index">排行榜</a></li>
                    <li><a asp-area="" asp-controller="Backend" asp-action="Index">后台管理</a></li>
                </ul>

                <div class="signin_add_a_r">
                    <a class="signin_add_a" asp-controller="UserGate" asp-action="SignOut">退出</a>
                    <a class="signin_add_a" asp-area="" asp-controller="UserGate" asp-action="ALogin">管理登录</a>
                </div>
                <div class="signin">
                    <img class="signin_userimg" src="~/images/user.png" />
                    <span class="s_caret"></span>
                    <div class="signin_add">
                        <a class="signin_add_a" asp-area="" asp-controller="UserGate" asp-action="CusLogin">用户登录</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - MovieTheater</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>